---
title: "The Impact of High School Sports"

---

   High School and being a teenager is a important and challenging time for young people. School sports is a great and infuential aspect of the school experience that can shape and impact youth. Playing and being apart of a team, winning and losing, and being in a competitve environment shape and challenge young minds and can impact them forever.
   
   A few things that young people learn, develop, and experience through High School Sports:
   
   1. Community - Students and kids get to be in an environment of others that have similiar passions. They get to be around others who can challenge them and build them up.
   2. Positive Mentors - A coach can be one of the most impactful and important people in a young person's life. They are able to instill life lessons, along with helping them grow as a person and athlete. 
   3. Impacts Academics - Students who particpate in sports in school seem to do better academically compared to those who are not partaking in athletics. 
   4. Time Management - Students learn to manage time better when they are apart of a team. They have to learn to use their time better around practice and games, trying to do homework, study, and other activities.
   5. Leadership - Students learn to lead their peers and teammates thorugh sports. Upperclassmen, having experience, can challenge and build up the younger players and set an example.
   
   These are just a few ways and examples of how students grow and are impacted thorugh school sports. To get more inforamtion go [here](https://www.publicschoolreview.com/blog/10-reasons-why-high-school-sports-benefit-students) to read more on this topic.


